authors:
  shenxianpeng:
    name: Xianpeng Shen
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/3353385?v=4
  2bndy5:
    name: Brendan Doherty
    description: Co-creator
    avatar: https://avatars.githubusercontent.com/u/14963867?v=4
